### ISSUE TITLE
Erro quando se usa o extends

### ISSUE THREAD

**Issue by filipevarjao** [ooerlang/ooerlang#1]
Está ocorrendo um erro sempre ao usar o extends, o próprio exemplo de teste apresenta o erro.
exemplos:

```
-class(horista).
-extends(empregado).
...
```

erro:
**exception error: no match of right hand side value undefined
    in function st:get_all_methods/1 (src/st.erl, line 183)
    in call from st:get_all_methods/1 (src/st.erl, line 184)
    in call from st:get_methods_with_parent/1 (src/st.erl, line 163)
    in call from core:create_all´_parent_methods/1 (src/core.erl, line 236)
    in call from core:transform_oast_to_east/3 (src/core.erl, 28)
    in call from ooec:get_erl_file_list/3 (src/ooec.erl, line 61)
    in call from ooec:compile/1 (src/ooec.erl, line 24)

**Comment by Filipergv** [comment]
Nop
